-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-02 16:42:37 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE game (
    game_name VARCHAR2(100) NOT NULL
);

ALTER TABLE game ADD CONSTRAINT game_pk PRIMARY KEY ( game_name );

CREATE TABLE gamegenre (
    game_name  VARCHAR2(100) NOT NULL,
    genre      VARCHAR2(50) NOT NULL
);

ALTER TABLE gamegenre ADD CONSTRAINT gamegenre_pk PRIMARY KEY ( game_name,
                                                                genre );

CREATE TABLE gameplatformpublisher (
    game_name  VARCHAR2(100) NOT NULL,
    platform   VARCHAR2(50) NOT NULL,
    publisher  VARCHAR2(75) NOT NULL
);

ALTER TABLE gameplatformpublisher
    ADD CONSTRAINT gameplatformpublisher_pk PRIMARY KEY ( platform,
                                                          game_name,
                                                          publisher );

CREATE TABLE gamesales (
    game_name        VARCHAR2(100) NOT NULL,
    platform         VARCHAR2(50) NOT NULL,
    publisher        VARCHAR2(75) NOT NULL,
    region           VARCHAR2(5) NOT NULL,
    year_of_release  INTEGER NOT NULL,
    region_sales     DECIMAL(5, 2)
);

ALTER TABLE gamesales
    ADD CONSTRAINT gamesales_pk PRIMARY KEY ( region,
                                              platform,
                                              game_name,
                                              publisher,
                                              year_of_release );

CREATE TABLE genre (
    genre VARCHAR2(50) NOT NULL
);

ALTER TABLE genre ADD CONSTRAINT genre_pk PRIMARY KEY ( genre );

CREATE TABLE platform (
    platform VARCHAR2(50) NOT NULL
);

ALTER TABLE platform ADD CONSTRAINT platform_pk PRIMARY KEY ( platform );

CREATE TABLE publisher (
    publisher VARCHAR2(75) NOT NULL
);

ALTER TABLE publisher ADD CONSTRAINT publisher_pk PRIMARY KEY ( publisher );

CREATE TABLE region (
    region VARCHAR2(5) NOT NULL
);

ALTER TABLE region ADD CONSTRAINT region_pk PRIMARY KEY ( region );

ALTER TABLE gamegenre
    ADD CONSTRAINT gamegenre_game_fk FOREIGN KEY ( game_name )
        REFERENCES game ( game_name );

ALTER TABLE gamegenre
    ADD CONSTRAINT gamegenre_genre_fk FOREIGN KEY ( genre )
        REFERENCES genre ( genre );

ALTER TABLE gameplatformpublisher
    ADD CONSTRAINT gameplatform_game_fk FOREIGN KEY ( game_name )
        REFERENCES game ( game_name );

ALTER TABLE gameplatformpublisher
    ADD CONSTRAINT gameplatform_platform_fk FOREIGN KEY ( platform )
        REFERENCES platform ( platform );

ALTER TABLE gameplatformpublisher
    ADD CONSTRAINT gameplatform_publisher_fk FOREIGN KEY ( publisher )
        REFERENCES publisher ( publisher );

ALTER TABLE gamesales
    ADD CONSTRAINT gamesales_gameplatform_fk FOREIGN KEY ( platform,
                                                           game_name,
                                                           publisher )
        REFERENCES gameplatformpublisher ( platform,
                                           game_name,
                                           publisher );

ALTER TABLE gamesales
    ADD CONSTRAINT gamesales_region_fk FOREIGN KEY ( region )
        REFERENCES region ( region );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
