-- GAMEDATA VIEW

CREATE OR REPLACE VIEW GAMEDATA AS
    SELECT
        GAMEGENRE.GAME_NAME,
        GAMEGENRE.GENRE,
        GAMESALES.PLATFORM,
        GAMESALES.PUBLISHER,
        GAMESALES.YEAR_OF_RELEASE,
        GAMESALES.REGION,
        GAMESALES.REGION_SALES
    FROM
        GAMEGENRE
    JOIN
        GAMESALES
    ON GAMESALES.game_name = GAMEGENRE.game_name;
    
